# Data Science and Machine Learning Capstone Project
## Project 1/Book 1  - Acquire data, clean it, save it to pickle format
<div style="text-align: right">
 Dan Thompson         </br> 
 danlthom@us.ibm.com  </br>
 August, 2019         </br>
</div>

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Pull down the NYC 311 data, using only the fields required for this assignment
#https://data.cityofnewyork.us/resource/fhrw-4uyv.csv?$limit=100000000&Agency=HPD&$select=created_date,unique_key,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,closed_date,location_type,status
#https://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/nyc_pluto_18v1.zip

Read the 311 data into a dataframe, identify which columns to use, explore the data, save it as a pickle file

In [13]:
filename = "~/Desktop/Notebooks/Capstone IBM/fhrw-4uyv.csv"
headers = ["created_date", "unique_key", "complaint_type", "incident_zip", "incident_address", "street_name", "address_type", "city", "resolution_description", "borough", "latitude", "longitude", "closed_date", "location_type", "status"]

df = pd.read_csv(filename, index_col = 1, names = headers, header=0, parse_dates=[0], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,13,14], dtype={2:str, 3:str, 4:str, 5:str, 6:str, 7:str, 8:str, 9:str, 10:float, 11:float, 13:str, 14:str })
df_hot = df[(df['complaint_type'] == 'HEATING') | (df['complaint_type'] == 'HEAT/HOT WATER')][['incident_address','incident_zip','created_date', 'latitude', 'longitude']]
df_hot.to_csv('./files/df_hot.csv')

In [164]:
df.head()

,created_date,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,location_type,status
unique_key,,,,,,,,,,,,,
43560297,2019-08-16 12:42:29,FLOORING/STAIRS,11691,711 SEAGIRT AVENUE,SEAGIRT AVENUE,ADDRESS,Far Rockaway,The following complaint conditions are still o...,QUEENS,40.595996,-73.742187,RESIDENTIAL BUILDING,Open
43568441,2019-08-16 11:30:45,FLOORING/STAIRS,10467,3150 ROCHAMBEAU AVENUE,ROCHAMBEAU AVENUE,ADDRESS,BRONX,The following complaint conditions are still o...,BRONX,40.874538,-73.880364,RESIDENTIAL BUILDING,Open
43560332,2019-08-16 10:46:02,WATER LEAK,10453,1841 DR M L KING JR BOULEVARD,DR M L KING JR BOULEVARD,ADDRESS,BRONX,The following complaint conditions are still o...,BRONX,40.851565,-73.914365,RESIDENTIAL BUILDING,Open
43566603,2019-08-16 10:14:53,PLUMBING,10455,774 FOX STREET,FOX STREET,ADDRESS,BRONX,The following complaint conditions are still o...,BRONX,40.816109,-73.897748,RESIDENTIAL BUILDING,Open
43563830,2019-08-16 12:27:53,UNSANITARY CONDITION,10025,311 WEST 95 STREET,WEST 95 STREET,ADDRESS,NEW YORK,The following complaint conditions are still o...,MANHATTAN,40.794797,-73.974188,RESIDENTIAL BUILDING,Open

In [165]:
df.shape

(5843263, 13)

In [160]:
df_311 = df
df_311.to_pickle('./files/df_311.pkl')

In [137]:
# Working with a smaller data set makes it easier to tweak the read_csv with proper column information
# but comment this out until you really need it
# df2 = pd.read_csv("~/Desktop/Notebooks/Capstone IBM/fhrw-4uyv-short.csv", index_col = 1, usecols=[0,1,3,4,5,6,7,8,9,10,11,13,14], names = headers, header=0, parse_dates=[0], dtype={2:str, 3:str, 4:str, 5:str, 6:str, 7:str, 8:str, 9:str, 10:float, 11:float, 13:str, 14:str })

## Get the pluto files

The pluto files give info about the buildings in NYC. There is one file per bourough. Read them all in, throw out the columns we do not need, then save them as pickle files.

In [4]:
pluto_files = ['BK_18v1.csv', 'BX_18v1.csv', 'MN_18v1.csv', 'QN_18v1.csv', 'SI_18v1.csv']

In [5]:
pluto_headers = ["Borough", "Block", "Lot", "CD", "CT2010", "CB2010", "SchoolDist", "Council", "ZipCode", "FireComp", "PolicePrct", "HealthCenterDistrict", "HealthArea", "SanitBoro", "SanitDistrict", "SanitSub", "Address", "ZoneDist1", "ZoneDist2", "ZoneDist3", "ZoneDist4", "Overlay1", "Overlay2", "SPDist1", "SPDist2", "SPDist3", "LtdHeight", "SplitZone", "BldgClass", "LandUse", "Easements", "OwnerType", "OwnerName", "LotArea", "BldgArea", "ComArea", "ResArea", "OfficeArea", "RetailArea", "GarageArea", "StrgeArea", "FactryArea", "OtherArea", "AreaSource", "NumBldgs", "NumFloors", "UnitsRes", "UnitsTotal", "LotFront", "LotDepth", "BldgFront", "BldgDepth", "Ext", "ProxCode", "IrrLotCode", "LotType", "BsmtCode", "AssessLand", "AssessTot", "ExemptLand", "ExemptTot", "YearBuilt", "YearAlter1", "YearAlter2", "HistDist", "Landmark", "BuiltFAR", "ResidFAR", "CommFAR", "FacilFAR", "BoroCode", "BBL", "CondoNo", "Tract2010", "XCoord", "YCoord", "ZoneMap", "ZMCode", "Sanborn", "TaxMap", "EDesigNum", "APPBBL", "APPDate", "PLUTOMapID", "FIRM07_FLAG", "PFIRM15_FLAG", "Version"]

pluto_cols = ["Address", "BldgArea", "BldgDepth", "BuiltFAR", "CommFAR", "FacilFAR", "Lot", "LotArea", "LotDepth", "NumBldgs", "NumFloors", "OfficeArea", "ResArea", "ResidFAR", "RetailArea", "YearBuilt", "YearAlter1", "ZipCode", "YCoord", "XCoord"]

In [11]:
# get just the columns we need for this part of the capstone


i = 0
for file in pluto_files:
    print("File ",file)
    df_pluto = pd.read_csv("~/Desktop/Notebooks/Capstone IBM/PLUTO_for_WEB/"+file, header=0, names = pluto_headers, 
                           usecols= pluto_cols,
                       dtype={"Address":str , "BldgArea":float , "BldgDepth":float , "BuiltFAR":float , 
                              "CommFAR":float , "FacilFAR":float , "Lot":int , "LotArea":float , 
                              "LotDepth":float , "NumBldgs":int , "NumFloors":float , "OfficeArea":float , 
                              "ResArea":float , "ResidFAR":float , "RetailArea":float , "YearBuilt":int , 
                              "YearAlter1":int , "ZipCode":str , "YCoord":str , "XCoord":str, 19:str ,
                              20:str ,22:str ,23:str ,24:str ,64:str ,65:str ,80:str, 25:str, 26:str, 77:str })
    
    if (i == 0):
        df_all = pd.DataFrame(data=df_pluto)
    else:
        df_all = df_all.append(df_pluto)
    i = i + 1
    
    pickle_name = file[:-3]+'pkl'
    print (pickle_name, df_pluto.shape, df_all.shape)
    df_pluto.to_pickle('./'+pickle_name)
    
    if (i == 5):
        df_all.to_pickle('./files/pluto_all.pkl')

File  BK_18v1.csv
BK_18v1.pkl (277316, 20) (277316, 20)
File  BX_18v1.csv
BX_18v1.pkl (89854, 20) (367170, 20)
File  MN_18v1.csv
MN_18v1.pkl (42966, 20) (410136, 20)
File  QN_18v1.csv
QN_18v1.pkl (324583, 20) (734719, 20)
File  SI_18v1.csv
SI_18v1.pkl (124493, 20) (859212, 20)

In [147]:
df_pluto[0:5]

,Lot,ZipCode,Address,LotArea,BldgArea,ResArea,OfficeArea,RetailArea,NumBldgs,NumFloors,LotDepth,BldgDepth,YearBuilt,YearAlter1,BuiltFAR,ResidFAR,CommFAR,FacilFAR,XCoord,YCoord
0,10,10301,139 BAY STREET,5716.0,18965.0,0,0,6965,1,4.0,84.0,50.0,1884,2000,3.32,2.43,3.4,4.8,963297,171951
1,17,10301,BAY STREET,780.0,0.0,0,0,0,0,0.0,35.0,0.0,0,0,0.00,2.43,3.4,4.8,NaN,NaN
2,18,10301,BAY STREET,520.0,0.0,0,0,0,0,0.0,25.0,0.0,0,0,0.00,2.43,3.4,4.8,NaN,NaN
3,19,10301,BAY STREET,278.0,0.0,0,0,0,0,0.0,15.0,0.0,0,0,0.00,2.43,3.4,4.8,NaN,NaN
4,21,10301,BAY STREET,6302.0,0.0,0,0,0,0,0.0,82.0,0.0,0,0,0.00,2.43,3.4,4.8,NaN,NaN